"""create docking tables

Revision ID: 075d4cc0643c
Revises: 
Create Date: 2026-02-01 02:46:50.256520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075d4cc0643c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docking_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=50), nullable=False),
    sa.Column('target_uniprot_id', sa.String(length=20), nullable=False),
    sa.Column('disease_name', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('grid_params_json', sa.Text(), nullable=True),
    sa.Column('docking_params_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('protein_pdbqt_path', sa.String(length=500), nullable=True),
    sa.Column('ligand_pdbqt_path', sa.String(length=500), nullable=True),
    sa.Column('output_pdbqt_path', sa.String(length=500), nullable=True),
    sa.Column('best_affinity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docking_jobs_best_affinity'), 'docking_jobs', ['best_affinity'], unique=False)
    op.create_index(op.f('ix_docking_jobs_candidate_id'), 'docking_jobs', ['candidate_id'], unique=False)
    op.create_index('ix_docking_jobs_candidate_target', 'docking_jobs', ['candidate_id', 'target_uniprot_id'], unique=False)
    op.create_index(op.f('ix_docking_jobs_created_at'), 'docking_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_docking_jobs_status'), 'docking_jobs', ['status'], unique=False)
    op.create_index('ix_docking_jobs_status_created', 'docking_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_docking_jobs_target_uniprot_id'), 'docking_jobs', ['target_uniprot_id'], unique=False)
    op.create_index(op.f('ix_docking_jobs_user_id'), 'docking_jobs', ['user_id'], unique=False)
    op.create_index('ix_docking_jobs_user_status', 'docking_jobs', ['user_id', 'status'], unique=False)
    op.create_table('docking_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('pose_number', sa.Integer(), nullable=False),
    sa.Column('binding_affinity', sa.Float(), nullable=False),
    sa.Column('rmsd_lb', sa.Float(), nullable=False),
    sa.Column('rmsd_ub', sa.Float(), nullable=False),
    sa.Column('pdbqt_file_path', sa.String(length=500), nullable=True),
    sa.Column('pdbqt_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['docking_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_docking_results_affinity', 'docking_results', ['binding_affinity'], unique=False)
    op.create_index(op.f('ix_docking_results_binding_affinity'), 'docking_results', ['binding_affinity'], unique=False)
    op.create_index(op.f('ix_docking_results_job_id'), 'docking_results', ['job_id'], unique=False)
    op.create_index('ix_docking_results_job_pose', 'docking_results', ['job_id', 'pose_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_docking_results_job_pose', table_name='docking_results')
    op.drop_index(op.f('ix_docking_results_job_id'), table_name='docking_results')
    op.drop_index(op.f('ix_docking_results_binding_affinity'), table_name='docking_results')
    op.drop_index('ix_docking_results_affinity', table_name='docking_results')
    op.drop_table('docking_results')
    op.drop_index('ix_docking_jobs_user_status', table_name='docking_jobs')
    op.drop_index(op.f('ix_docking_jobs_user_id'), table_name='docking_jobs')
    op.drop_index(op.f('ix_docking_jobs_target_uniprot_id'), table_name='docking_jobs')
    op.drop_index('ix_docking_jobs_status_created', table_name='docking_jobs')
    op.drop_index(op.f('ix_docking_jobs_status'), table_name='docking_jobs')
    op.drop_index(op.f('ix_docking_jobs_created_at'), table_name='docking_jobs')
    op.drop_index('ix_docking_jobs_candidate_target', table_name='docking_jobs')
    op.drop_index(op.f('ix_docking_jobs_candidate_id'), table_name='docking_jobs')
    op.drop_index(op.f('ix_docking_jobs_best_affinity'), table_name='docking_jobs')
    op.drop_table('docking_jobs')
    # ### end Alembic commands ###
